/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/navbar/AppMenu.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    CustomDropDown: typeof import('./src/components/CustomDropDown.vue')['default']
    CustomDropzone: typeof import('./src/components/CustomDropzone.vue')['default']
    CustomFlatpicker: typeof import('./src/components/CustomFlatpicker.vue')['default']
    CustomGLightbox: typeof import('./src/components/CustomGLightbox.vue')['default']
    CustomStepper: typeof import('./src/components/CustomStepper.vue')['default']
    CustomStickyElement: typeof import('./src/components/CustomStickyElement.vue')['default']
    CustomTinySlider: typeof import('./src/components/CustomTinySlider.vue')['default']
    GuestAndRoomForm: typeof import('./src/components/GuestAndRoomForm.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    MenuItem: typeof import('./src/components/navbar/MenuItem.vue')['default']
    MenuItemLink: typeof import('./src/components/navbar/MenuItemLink.vue')['default']
    MenuItemWithChildren: typeof import('./src/components/navbar/MenuItemWithChildren.vue')['default']
    MobileMenu: typeof import('./src/components/navbar/mobile-menu/MobileMenu.vue')['default']
    MobileMenuItem: typeof import('./src/components/navbar/mobile-menu/MobileMenuItem.vue')['default']
    MobileMenuItemLink: typeof import('./src/components/navbar/mobile-menu/MobileMenuItemLink.vue')['default']
    MobileMenuItemWithChildren: typeof import('./src/components/navbar/mobile-menu/MobileMenuItemWithChildren.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFormInput: typeof import('./src/components/SelectFormInput.vue')['default']
    VerticalMenu: typeof import('./src/components/navbar/mobile-menu/VerticalMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBPopover: typeof import('bootstrap-vue-next')['vBPopover']
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
